### ISSUE TITLE
Any chances it will be in AUR?

### ISSUE THREAD

**Issue by mrlamud** [jonian/kickoff-player#1]
It will be highly appreciate.

**Comment by jonian** [comment]
Hi, thank you for your interest.

Yes, I will publish this in the AUR. Right now it is not ready for use, since it is not finished and it has some bugs. I will try to have it ready for the new season!

I will close this issue when it will be published in the AUR.

**Comment by mrlamud** [comment]
Thanks for  all your great jobs, ever. I'll keep waiting for it.

**Comment by jonian** [comment]
Here is a git package for AUR.
https://aur.archlinux.org/packages/kickoff-player-git/

I will release another package for the stable version when it is ready.

**Comment by mrlamud** [comment]
Wow!!! Thanks a lot.
![screenshot from 2017-08-11 20-01-44](https://user-images.githubusercontent.com/10531175/29214039-f8ee6968-7ecf-11e7-9085-a924496d01a7.png)
