### ISSUE TITLE
High CPU usage.

### ISSUE THREAD

**Issue by mrlamud** [jonian/kickoff-player#3]
CPU core i5 with IGP, kickoff-player uses a lot of CPU.
F.Y.I - room's temperature is at 32 degree Celsius.

![screenshot from 2017-08-12 19-36-36](https://user-images.githubusercontent.com/10531175/29240771-ef7a0f1a-7f95-11e7-905c-386c0da8567d.png)

**Comment by jonian** [comment]
Hi, thank you for the report.

I have disabled automatic score updates since it was causing various issues including high cpu usage.
Please confirm if it fixes the issue for you.

**Comment by mrlamud** [comment]
Yes it fixes. 
Thank you.
![screenshot from 2017-08-13 06-29-53](https://user-images.githubusercontent.com/10531175/29244918-5cda5a6e-7ff1-11e7-96a4-508f56d560c3.png)
