### ISSUE TITLE
kickoff-player-git r155.fbfbe8d-1pcakge repeats re-installing.

### ISSUE THREAD

**Issue by mrlamud** [jonian/kickoff-player#5]
Everytime I check for update using pacaur, Kickoff-player-git r155.fbfbe8d-1 repeats re-installing.

**Comment by jonian** [comment]
I can not reproduce this.

Do you use `pacaur -Syu` or `pacaur -Syu --devel` to check for updates? If you use the second, it always reinstalls `-git` packages.

You can also try to clear aur cache with `pacaur -Scc` and see if it helps.

**Comment by mrlamud** [comment]
Always uses -Syu. Neither pacaur-Scc nor update mirrorlist helps.
It's so confusing.

**Comment by jonian** [comment]
I managed to reproduce this and fixed the AUR package. You can update and close this issue if it is fixed.

**Comment by mrlamud** [comment]
Thanks for quick fixing.
