### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by joaojotta** [jonian/kickoff-player#7]
So, I was all hyped about this but it just won't start.

When going from termial, this is what I get after `kickoff-player URL`

`Traceback (most recent call last):
  File "/usr/bin/kickoff-player", line 109, in <module>
    player = KickoffPlayer()
  File "/usr/bin/kickoff-player", line 56, in __init__
    self.player   = PlayerHandler(self)
  File "/opt/kickoff-player-git/handlers/player.py", line 42, in __init__
    self.playbin = GstBox(callback=self.update_status)
  File "/opt/kickoff-player-git/widgets/gstbox.py", line 22, in __init__
    self.swidget = self.gtksink.props.widget
AttributeError: 'NoneType' object has no attribute 'props'`

Am I getting the URL wrong?
Isn't it like "acesteam://23045892347076"?

Thanks

**Comment by jonian** [comment]
Hi, I looks like you are missing gstreamer.

Can you provide more info, like:
- Distro
- Installation method
- Installed Gstreamer packages

*Update: `gtksink` is in `gst-plugins-bad`. I will add it into readme requirements. https://gstreamer.freedesktop.org/documentation/plugins.html

**Comment by joaojotta** [comment]
I'm on Arch and I installed it with Arch Anywhere.
GStreamer is there.
Packages (the ones I can identify):
```
gstreamer
gst-plugins-base-libs
```
All the dependencies are installed but now that I mention this:
`warning: gtk3-3.22.21-1 is up to date -- reinstalling
warning: gstreamer-1.12.2-1 is up to date -- reinstalling
warning: python-3.6.2-1 is up to date -- reinstalling
warning: python-gobject-3.24.1-1 is up to date -- reinstalling
warning: python-psutil-5.3.1-1 is up to date -- reinstalling
warning: python-pexpect-4.2.1-2 is up to date -- reinstalling
warning: python-peewee-2.10.1-1 is up to date -- reinstalling
warning: python-requests-2.18.4-1 is up to date -- reinstalling
error: target not found: python-fuzzywuzzy
warning: python-levenshtein-0.12.0-4 is up to date -- reinstalling
warning: python-dateutil-2.6.1-1 is up to date -- reinstalling
warning: python-lxml-3.8.0-2 is up to date -- reinstalling
error: target not found: acestream-engine
warning: sopcast-3.2.6-1 is up to date -- reinstalling`

Acestream itself is running well when I open the links and tell it to open via acestream-launcher and VLC pops up.
The `python-fuzzywuzzy` is installed. I `yaourt python-fuzzywuzzy` and it's flagged as installed.

Sorry if this isn't help enough but I'm not that technical.

**Comment by jonian** [comment]
Install `gst-plugins-bad` and it will work. `pacman -S gst-plugins-bad`.

If you installed kickoff-player from AUR, just update the AUR package, I have fixed it to include gst-plugins-bad in dependencies.

**Comment by joaojotta** [comment]
NICE!!! It worked!!!
(stuck at buffering but the software itself works)

Thanks a lot, man!!
