### ISSUE TITLE
Closes right after start

### ISSUE THREAD

**Issue by jppmarujo** [jonian/kickoff-player#8]
Hey Jonian,

First of all, the hype about this project made me register to github. :) 
I installed the package via AUR, and already checked other closed issues, mainly regarding gst-plugins (i have all the required), and also gstreamer.

Still, when i try to start the program (i'm on Antergos, KDE 5.11.1), the icon shows up in the taskbar just to close after few seconds.

If i can provide you any output to further investigate what's happening, please tell me what. 

Thanks for any assistance you can provide.

**Comment by jonian** [comment]
Hi @jppmarujo,

Thank you for reporting the issue. Could you please launch the app from the terminal with `kickoff-player` and post the output?

**Comment by jppmarujo** [comment]
Sure, no problem.

```
kickoff-player

(kickoff-player:11223): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(kickoff-player:11223): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(kickoff-player:11223): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/bin/kickoff-player", line 16, in <module>
    from handlers.player import PlayerHandler
  File "/opt/kickoff-player-git/handlers/player.py", line 2, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

**Comment by jonian** [comment]
Thanks for the quick response.

The package `python-dbus` is missing. I added it to the readme and updated the AUR package.
Update from AUR and close this issue if it is fixed.

**Comment by jppmarujo** [comment]
It is fixed. 
Thank you for your quick reply, the fix time was amazing, and also for this great project.
