### ISSUE TITLE
Stream Unavailable

### ISSUE THREAD

**Issue by nheolinkin** [jonian/kickoff-player#9]
I installed kickoff-player-git (179.b9536e2) from AUR and I can not play any stream.
It just kept saying "Stream Unavailable" with both acestream and sopcast link.

This is what I got from journalctl:
**Nov 01 04:09:42 arch acestreamengine[17509]: 2017-11-01 04:09:42,626|MainThread|acestream|error during startup
Nov 01 04:09:42 arch acestreamengine[17509]: Traceback (most recent call last):
Nov 01 04:09:42 arch acestreamengine[17509]:   File "core.c", line 1590, in
Nov 01 04:09:42 arch acestreamengine[17509]:   File "core.c", line 144, in
Nov 01 04:09:42 arch acestreamengine[17509]:   File "core.c", line 2, in
Nov 01 04:09:42 arch acestreamengine[17509]: ImportError: cannot import name __m2cr**

**Comment by jonian** [comment]
Hi @nheolinkin, this is an issue with [acestream-engine](https://aur.archlinux.org/packages/acestream-engine) package.

You have to downgrade `python2-m2crypto` to version 0.23 or you can use this [PKGBUILD](https://gist.github.com/maccyber/c20c5d2f04686f7bf0dadbfeb5e57880) to install acestream-engine without downgrading. Check the discussion [here](https://aur.archlinux.org/packages/acestream-engine).
